@startuml
actor User
User -> CityBoom: start
loop
    CityBoom -> Game: go()
    Game --> CityBoom: city
    CityBoom --> User: wait input
    User -> CityBoom: name
    CityBoom -> Game: examine(name)
    Game --> CityBoom: city
end
@enduml